#!/usr/bin/bash

init="$(($(cat /sys/class/net/[ew]*/statistics/rx_bytes | paste -sd '+')))"
printf "Recording bandwidth. Press enter to stop"

read -r key

end="$(($(cat /sys/class/net/[ew]*/statistics/rx_bytes | paste -sd '+')))"
printf "%4sB of bandwidth used.\\n" $(numfmt --to=iec $(($end-$init)))
